version: '3.5'

services:
  sscan-nest:
    build: 
      context: nest
    container_name: sscan-nest
    restart: always
    networks:
      - nwk
    ports:
      - '127.0.0.1:${NEST_PORT}:${NEST_PORT}'
    volumes:
      - ./nest/scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - nest-temp:/tmp
    env_file:
      - .env
  
  sscan-ipfs:
    image: ipfs/go-ipfs:v0.24.0
    container_name: sscan-ipfs
    restart: always
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    networks:
      - nwk
    ports:
      - "127.0.0.1:${IPFS_PORT}:${IPFS_PORT}"
      - "${SWARM_PORT}:${SWARM_PORT}"
      - "127.0.0.1:${GATE_PORT}:${GATE_PORT}"
    volumes:
      - ./docker-data/ipfs:/ipfsdata
  
  sscan-nginx:
    image: nginx:1.25
    container_name: sscan-nginx
    restart: always
    ports:
      - '127.0.0.1:${NGINX_PORT}:${NGINX_PORT}'
    networks:
      - nwk
    volumes:
      - ./nginx/:/etc/nginx/templates/
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NEST_PORT=${NEST_PORT}
      - GATE_PORT=${GATE_PORT}
  
  contract-builder:
    image: sourcescan/rust-builder:cargo-near0.5.0
    container_name: contract-builder
    restart: always
    networks:
      - nwk
    volumes_from:
      - sscan-nest
    stdin_open: true
    tty: true

volumes:
  nest-temp:
    driver: local

networks:
  nwk:
    driver: bridge
