import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';
import GithubData from '../modules/near/interfaces/github-data.interface';

export class GenKeyDto {
  @ApiProperty({
    description: 'Jwt auth token generated by /temp api',
    example: 'dadakfkakfk29a9lflafl',
  })
  @IsNotEmpty()
  @IsString()
  accessToken: string;

  @ApiProperty({
    description: 'Programming language used',
    example: 'rust or ts',
  })
  @IsNotEmpty()
  @IsString()
  lang: string;

  @ApiProperty({
    description: 'Entry point',
    example: 'Cargo.toml or package.json',
  })
  @IsNotEmpty()
  @IsString()
  entryPoint: string;

  @ApiProperty({
    description: 'GitHub repository URL',
    example: 'https://github.com/SourceScan/verifier-contract',
  })
  @IsNotEmpty()
  github: GithubData;

  @ApiProperty({
    description: 'Account ID associated with the request',
    example: 'sourcescan.near',
  })
  @IsNotEmpty()
  @IsString()
  accountId: string;
}
